export default [
  {
    company: `Tradier`,
    location: `Charlotte, North Carolina`,
    isRemote: true,
    url: `https://tradier.com`,
    startDate: `February 2021`,
    endDate: `March 2025`,
    title: `Senior Frontend Developer`,
    listItems: [
      `Optimized performance by replacing Ember applications with Vue applications, reducing feature development time from 2+ weeks to under a week.`,
      `Enhanced frontend architecture for frontend platform, leading to 25% improvement in load times and user engagement metrics`,
      `Produced dynamic, single-page applications utilizing proven and emerging technology, reducing bounce rates by 10%`,
      `Mentored 2 junior developers while conducting code reviews, fostering a culture of continuous learning and collaboration within the team`,
      `Partnered with UX/UI designers to translate design wireframes into responsive, interactive web applications, boosting user experience`,
    ],
  },
  {
    company: `Ample`,
    location: `Cincinnati, Ohio`,
    isRemote: true,
    url: `https://www.ample.co`,
    startDate: `October 2019`,
    endDate: `February 2021`,
    title: `Engineering Director`,
    listItems: [
      `Maximized reach by assisting the church to transition to online services and content during the COVID pandemic, resulting in a 35% bump in usage of web properties`,
      `Directed engineering operations for a team of 10 developers to provide technical decision-making, driving project success and efficiency improvements through strategic leadership and collaboration`,
      `Implemented agile methodologies to streamline development processes, resulting in a 20% increase in project delivery speed`,
      `Oversaw the design and implementation of complex web applications using React and Gatsby, improving user experience and functionality`,
      `Spearheaded career progression with targeted professional development, allowing team members to build technical skills`,
    ],
  },
  {
    company: `Matchbox Design Group`,
    location: `Saint Louis, MO`,
    isRemote: false,
    url: `https://matchboxdesigngroup.com/`,
    startDate: `November 2012`,
    endDate: `October 2019`,
    title: `Lead Developer`,
    listItems: [
      `Decreased bounce rates by an average of 25% by optimizing website performance, earning a 90+ score on Google PageSpeed Insights`,
      `Facilitated automatic inventory updates by integrating AS400 systems, expertly meeting client needs`,
      `Led cross-functional teams in the development and execution of strategic initiatives, leading to a 15% increase in project efficiency`,
      `Generated intuitive and user-friendly custom websites with WordPress, Laravel, and Vue, successfully managing 50+ projects to stay within required deadlines`,
      `Promoted seamless communication and workflow while working closely with diverse clients, cutting launch times by 15%`,
    ],
  },
];
