import { SKILLS } from "./skills";
export default [
  {
    company: `Tradier`,
    imageUrl: `dash.png`,
    url: `https://dash.tradier.com`,
    slug: "dash",
    skills: [
      SKILLS.VUE_JS,
      SKILLS.TAILWIND_CSS,
      SKILLS.VITE,
      SKILLS.VITEST,
      SKILLS.JAVASCRIPT,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Tradier Web`,
    content: `Tradier Web, our main Trading platform and my primary responsibility at Tradier. Built using [Vue.js](https://vuejs.org) and [Tailwind.css](https://tailwindcss.com).`,
  },
  {
    company: `Ample`,
    imageUrl: `crossroads.png`,
    url: `https://www.crossroads.net/`,
    slug: "crossroads",
    skills: [
      SKILLS.JEKYLL,
      SKILLS.JAMSTACK,
      SKILLS.HTML,
      SKILLS.CSS,
      SKILLS.JAVASCRIPT,
      SKILLS.GATSBY,
      SKILLS.GRAPHQL,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Crossroads Church`,
    content: `Crossroads Church is a Church in Cincinnati, OH. I worked on one of 4 teams where my primary focus on the front-end experience.`,
  },
  {
    company: `Ample`,
    imageUrl: `mikealbert.png`,
    url: `https://www.mikealbert.com/`,
    slug: "mikealbert",
    skills: [
      SKILLS.REACT,
      SKILLS.JAMSTACK,
      SKILLS.CSS,
      SKILLS.JAVASCRIPT,
      SKILLS.GATSBY,
      SKILLS.GRAPHQL,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Mike Albert Fleet Solutions`,
    content: `Mike Albert is a Fleet Solutions company in Cincinnati, OH. I was responsible for rebuilding and mantling the site. Built with [Gatsby](https://www.gatsbyjs.com/) and [DatoCMS](https://www.datocms.com/) as the CMS backend.`,
  },
  {
    company: `Matchbox Design Group`,
    imageUrl: `ehggear.png`,
    url: `http://ehggear.com/`,
    slug: "ehggear",
    skills: [
      SKILLS.WORDPRESS,
      SKILLS.VUE_JS,
      SKILLS.WOOCOMMERCE,
      SKILLS.TAILWIND_CSS,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Engineered Hunting Gear`,
    content: `Engineered Hunting Gear (EHG) is an e-commerce site that sells outdoor clothing. Built using [WordPress](https://wordpress.org/), [WooCommerce](https://woocommerce.com/), [Tailwinds.css](https://tailwindcss.com/) and some [Vue.js](https://vuejs.org/). I was responsible for setting up the majority of WooCommerce. Along with building the filters, product quick view and color swatch picker all in Vue.js. I built them into a must-use plugin with the plan of re-using it for other e-commerce sites.`,
  },
  {
    company: `Matchbox Design Group`,
    imageUrl: `firmexchange.png`,
    url: `https://firmexchange.com/`,
    slug: "firmexchange",
    skills: [
      SKILLS.LARAVEL,
      SKILLS.VUE_JS,
      SKILLS.ALGOLIA,
      SKILLS.WORDPRESS,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Firm Exchange`,
    content: `Firm Exchange is a business sale platform. It's like [Trulia](https://www.trulia.com/) for businesses. I was responsible for building the majority of the application. I built it using [Laravel](https://laravel.com/) and Vue.js. The search uses [Algolia](https://www.algolia.com/) via [Laravel Scout](https://laravel.com/docs/5.8/scout) with geo-search capability added in. I built the blog using [WordPress](https://wordpress.org/) and a simple API to sync the header, footer and styles. This allowed the blog to stay in sync with the main application.`,
  },
  {
    company: `Matchbox Design Group`,
    imageUrl: `imperialsports.png`,
    url: `https://imperialsports.com/`,
    slug: "imperialsports",
    skills: [
      SKILLS.WORDPRESS,
      SKILLS.WOOCOMMERCE,
      SKILLS.VUE_JS,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Imperial Sports`,
    content: `Imperial Sports is an e-commerce site built with [WordPress](https://wordpress.org/), [WooCommerce](https://woocommerce.com/) and [Vue.js](https://vuejs.org/). That sells hats, shirts and other items. I was responsible for building out parts of the original site. Along with adding features over the past 4+ years. An [EDI](https://en.wikipedia.org/wiki/Electronic_data_interchange) integration with the internal inventory system. A product builder that allows customers to add logos and text to products. An inventory sync system to keep the stock levels in sync with the internal inventory system. Custom integration with WooCommerce to add general features.`,
  },
  {
    company: `Matchbox Design Group`,
    imageUrl: `industrialsoap.png`,
    url: `https://industrialsoap.com/`,
    slug: "industrialsoap",
    skills: [
      SKILLS.WORDPRESS,
      SKILLS.WOOCOMMERCE,
      SKILLS.ARCHITECTURE,
      SKILLS.MENTORSHIP,
      SKILLS.LEADERSHIP,
    ],
    title: `Industrial Soap Company`,
    content: `The Industrial Soap Company site is an e-commerce site built with [WordPress](https://wordpress.org/) and [WooCommerce](https://woocommerce.com/). I was responsible for the majority of the store product and ordering functionality. Each customer on the site has access to different products at different prices defined in their contract. This required a large amount of WooCommerce customization to restrict access to certain products. Along with building a table of all available products. Where customers could order multiple products at a time. I built sync to keep the contract prices and products in sync. Along with an inventory, sync to keep the stock levels up to date.`,
  },
  {
    company: `Matchbox Design Group`,
    imageUrl: `kindling.png`,
    slug: "kindling",
    skills: [SKILLS.WORDPRESS, SKILLS.LARAVEL, SKILLS.TAILWIND_CSS],
    title: `Kindling WordPress Framework`,
    content: `Kindling is a custom [WordPress](https://wordpress.org/) framework that I have maintained over the years. This has been the foundation for all WordPress related projects. It uses Composer to integrate parts of [Laravel] to make building with WordPress a little nicer. It brings in the Laravel [Blade](https://laravel.com/docs/blade), [Service Container](https://laravel.com/docs/container), [Router](https://laravel.com/docs/routing) and more. It uses [Laravel Mix](https://laravel.com/docs/mix) to allow us to compile our front-end assets. It has a custom post type system to try to enforce sensible defaults. This helps to streamline the setup and boilerplate required. Such as adding a default category custom taxonomy. It also adds a default base [Tailwind.css](https://tailwindcss.com/) setup to help with consistency between projects.`,
  },
  {
    company: `Matchbox Design Group`,
    imageUrl: `moversstudy.png`,
    url: `https://moversstudy.unitedvanlines.com/`,
    slug: "moversstudy",
    skills: [SKILLS.WORDPRESS, SKILLS.VUE_JS, SKILLS.TAILWIND_CSS],
    title: `Movers Study United Van Lines`,
    content: `The Movers Study micro-site is an informational map showing data collected from the United Van Lines Mover Study. I was responsible for building out all the functionality of the site. I built it using [WordPress](https://wordpress.org/), [Tailwinds.css](https://tailwindcss.com/) and [Vue.js](https://vuejs.org/). It allows for admins to add new data each year. The map will allow users to see the change in migration patterns over time.`,
  },
];
